In [2]:
import numpy as np

In [9]:
nda = np.array([1,2,3])
type(nda)

numpy.ndarray

In [10]:
nda

array([1, 2, 3])

In [11]:
ndb = np.array([[1,2,3],[4,5,6],[7,8,9]])
ndb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ndb.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
ndc = np.array([1.1, 2.2, 3.3])
ndc

array([1.1, 2.2, 3.3])

In [14]:
print(nda.dtype)
print(ndc.dtype)

int64
float64


In [27]:
for i in ndb.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [24]:
t = ndb.T
print(t)
print(t.flat)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [29]:
t.ndim

2

In [30]:
t.shape

(3, 3)